//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electros.FaultsServ {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FaultsServ.IFaultReportLogService")]
    public interface IFaultReportLogService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaultReportLogService/Create", ReplyAction="http://tempuri.org/IFaultReportLogService/CreateResponse")]
        void Create(Common.FaultReport faultReport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaultReportLogService/CreateLog", ReplyAction="http://tempuri.org/IFaultReportLogService/CreateLogResponse")]
        void CreateLog(Common.FaultLog faultLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaultReportLogService/GenerateTicketNum", ReplyAction="http://tempuri.org/IFaultReportLogService/GenerateTicketNumResponse")]
        int GenerateTicketNum();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaultReportLogService/getTicketNum", ReplyAction="http://tempuri.org/IFaultReportLogService/getTicketNumResponse")]
        Common.FaultReport getTicketNum(int ticketNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaultReportLogService/getFaultReportIDByAccountIDTicket", ReplyAction="http://tempuri.org/IFaultReportLogService/getFaultReportIDByAccountIDTicketRespon" +
            "se")]
        Common.FaultReport getFaultReportIDByAccountIDTicket(int accountID, int ticketNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaultReportLogService/getFaultLogByReportID", ReplyAction="http://tempuri.org/IFaultReportLogService/getFaultLogByReportIDResponse")]
        Common.FaultLog[] getFaultLogByReportID(int frID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaultReportLogService/getFaultLogs", ReplyAction="http://tempuri.org/IFaultReportLogService/getFaultLogsResponse")]
        Common.FaultLog[] getFaultLogs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaultReportLogService/getFaultReportIDByAccountID", ReplyAction="http://tempuri.org/IFaultReportLogService/getFaultReportIDByAccountIDResponse")]
        Common.FaultReport[] getFaultReportIDByAccountID(int accountID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaultReportLogService/getFaultByID", ReplyAction="http://tempuri.org/IFaultReportLogService/getFaultByIDResponse")]
        Common.FaultReport getFaultByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaultReportLogService/searchLogByDates", ReplyAction="http://tempuri.org/IFaultReportLogService/searchLogByDatesResponse")]
        Common.FaultLog[] searchLogByDates(System.DateTime dateFrom, System.DateTime dateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaultReportLogService/search", ReplyAction="http://tempuri.org/IFaultReportLogService/searchResponse")]
        Common.FaultLog[] search(int accountID, int reportID, System.DateTime dateFrom, System.DateTime dateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaultReportLogService/sortByDate", ReplyAction="http://tempuri.org/IFaultReportLogService/sortByDateResponse")]
        Common.FaultLog[] sortByDate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaultReportLogService/getFaultByAccountIDPRoductID", ReplyAction="http://tempuri.org/IFaultReportLogService/getFaultByAccountIDPRoductIDResponse")]
        Common.FaultReport[] getFaultByAccountIDPRoductID(int accountID, int productID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFaultReportLogServiceChannel : Electros.FaultsServ.IFaultReportLogService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FaultReportLogServiceClient : System.ServiceModel.ClientBase<Electros.FaultsServ.IFaultReportLogService>, Electros.FaultsServ.IFaultReportLogService {
        
        public FaultReportLogServiceClient() {
        }
        
        public FaultReportLogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FaultReportLogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FaultReportLogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FaultReportLogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Create(Common.FaultReport faultReport) {
            base.Channel.Create(faultReport);
        }
        
        public void CreateLog(Common.FaultLog faultLog) {
            base.Channel.CreateLog(faultLog);
        }
        
        public int GenerateTicketNum() {
            return base.Channel.GenerateTicketNum();
        }
        
        public Common.FaultReport getTicketNum(int ticketNum) {
            return base.Channel.getTicketNum(ticketNum);
        }
        
        public Common.FaultReport getFaultReportIDByAccountIDTicket(int accountID, int ticketNum) {
            return base.Channel.getFaultReportIDByAccountIDTicket(accountID, ticketNum);
        }
        
        public Common.FaultLog[] getFaultLogByReportID(int frID) {
            return base.Channel.getFaultLogByReportID(frID);
        }
        
        public Common.FaultLog[] getFaultLogs() {
            return base.Channel.getFaultLogs();
        }
        
        public Common.FaultReport[] getFaultReportIDByAccountID(int accountID) {
            return base.Channel.getFaultReportIDByAccountID(accountID);
        }
        
        public Common.FaultReport getFaultByID(int id) {
            return base.Channel.getFaultByID(id);
        }
        
        public Common.FaultLog[] searchLogByDates(System.DateTime dateFrom, System.DateTime dateTo) {
            return base.Channel.searchLogByDates(dateFrom, dateTo);
        }
        
        public Common.FaultLog[] search(int accountID, int reportID, System.DateTime dateFrom, System.DateTime dateTo) {
            return base.Channel.search(accountID, reportID, dateFrom, dateTo);
        }
        
        public Common.FaultLog[] sortByDate() {
            return base.Channel.sortByDate();
        }
        
        public Common.FaultReport[] getFaultByAccountIDPRoductID(int accountID, int productID) {
            return base.Channel.getFaultByAccountIDPRoductID(accountID, productID);
        }
    }
}
