//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electros.UserServ {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServ.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Create", ReplyAction="http://tempuri.org/IUserService/CreateResponse")]
        void Create(Common.User user, int[] roles, Common.Account a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/getAccountByUsername", ReplyAction="http://tempuri.org/IUserService/getAccountByUsernameResponse")]
        Common.Account getAccountByUsername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/getUserByEmail", ReplyAction="http://tempuri.org/IUserService/getUserByEmailResponse")]
        Common.User getUserByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/getUSerByAccountID", ReplyAction="http://tempuri.org/IUserService/getUSerByAccountIDResponse")]
        Common.User getUSerByAccountID(int accountID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : Electros.UserServ.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<Electros.UserServ.IUserService>, Electros.UserServ.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Create(Common.User user, int[] roles, Common.Account a) {
            base.Channel.Create(user, roles, a);
        }
        
        public Common.Account getAccountByUsername(string username) {
            return base.Channel.getAccountByUsername(username);
        }
        
        public Common.User getUserByEmail(string email) {
            return base.Channel.getUserByEmail(email);
        }
        
        public Common.User getUSerByAccountID(int accountID) {
            return base.Channel.getUSerByAccountID(accountID);
        }
    }
}
