//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electros.FaultServ {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FaultServ.IFaultReportLogService")]
    public interface IFaultReportLogService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaultReportLogService/Create", ReplyAction="http://tempuri.org/IFaultReportLogService/CreateResponse")]
        void Create(Common.FaultReport faultReport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaultReportLogService/CreateLog", ReplyAction="http://tempuri.org/IFaultReportLogService/CreateLogResponse")]
        void CreateLog(Common.FaultLog faultLog);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFaultReportLogServiceChannel : Electros.FaultServ.IFaultReportLogService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FaultReportLogServiceClient : System.ServiceModel.ClientBase<Electros.FaultServ.IFaultReportLogService>, Electros.FaultServ.IFaultReportLogService {
        
        public FaultReportLogServiceClient() {
        }
        
        public FaultReportLogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FaultReportLogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FaultReportLogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FaultReportLogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Create(Common.FaultReport faultReport) {
            base.Channel.Create(faultReport);
        }
        
        public void CreateLog(Common.FaultLog faultLog) {
            base.Channel.CreateLog(faultLog);
        }
    }
}
