//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electros.ProductOrderServ {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductOrderServ.IProductOrder")]
    public interface IProductOrder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductOrder/addOrder", ReplyAction="http://tempuri.org/IProductOrder/addOrderResponse")]
        void addOrder(Common.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductOrder/addProductOrder", ReplyAction="http://tempuri.org/IProductOrder/addProductOrderResponse")]
        void addProductOrder(Common.ProductOrder productOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductOrder/getOrderIDByAccountIDStatus", ReplyAction="http://tempuri.org/IProductOrder/getOrderIDByAccountIDStatusResponse")]
        Common.Order getOrderIDByAccountIDStatus(int accountID, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductOrder/DeleteProductOrder", ReplyAction="http://tempuri.org/IProductOrder/DeleteProductOrderResponse")]
        void DeleteProductOrder(Common.ProductOrder productOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductOrder/getProductOrderID", ReplyAction="http://tempuri.org/IProductOrder/getProductOrderIDResponse")]
        Common.ProductOrder getProductOrderID(int productID, int orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductOrder/UpdateProductOrder", ReplyAction="http://tempuri.org/IProductOrder/UpdateProductOrderResponse")]
        void UpdateProductOrder(Common.ProductOrder po);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductOrder/getUserProductOrder", ReplyAction="http://tempuri.org/IProductOrder/getUserProductOrderResponse")]
        Common.Order getUserProductOrder(int accountID, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductOrder/getProductOrderByOrderID", ReplyAction="http://tempuri.org/IProductOrder/getProductOrderByOrderIDResponse")]
        Common.ProductOrder[] getProductOrderByOrderID(int orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductOrder/DeleteProductOrderByIDs", ReplyAction="http://tempuri.org/IProductOrder/DeleteProductOrderByIDsResponse")]
        void DeleteProductOrderByIDs(int productID, int orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductOrder/UpdateOrder", ReplyAction="http://tempuri.org/IProductOrder/UpdateOrderResponse")]
        void UpdateOrder(Common.Order o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductOrder/getShippedOrders", ReplyAction="http://tempuri.org/IProductOrder/getShippedOrdersResponse")]
        Common.Order[] getShippedOrders(int accountID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductOrder/getPurchasesUnderWarranty", ReplyAction="http://tempuri.org/IProductOrder/getPurchasesUnderWarrantyResponse")]
        Common.Order[] getPurchasesUnderWarranty(int accountID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductOrderChannel : Electros.ProductOrderServ.IProductOrder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductOrderClient : System.ServiceModel.ClientBase<Electros.ProductOrderServ.IProductOrder>, Electros.ProductOrderServ.IProductOrder {
        
        public ProductOrderClient() {
        }
        
        public ProductOrderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductOrderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductOrderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductOrderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void addOrder(Common.Order order) {
            base.Channel.addOrder(order);
        }
        
        public void addProductOrder(Common.ProductOrder productOrder) {
            base.Channel.addProductOrder(productOrder);
        }
        
        public Common.Order getOrderIDByAccountIDStatus(int accountID, string status) {
            return base.Channel.getOrderIDByAccountIDStatus(accountID, status);
        }
        
        public void DeleteProductOrder(Common.ProductOrder productOrder) {
            base.Channel.DeleteProductOrder(productOrder);
        }
        
        public Common.ProductOrder getProductOrderID(int productID, int orderID) {
            return base.Channel.getProductOrderID(productID, orderID);
        }
        
        public void UpdateProductOrder(Common.ProductOrder po) {
            base.Channel.UpdateProductOrder(po);
        }
        
        public Common.Order getUserProductOrder(int accountID, string status) {
            return base.Channel.getUserProductOrder(accountID, status);
        }
        
        public Common.ProductOrder[] getProductOrderByOrderID(int orderID) {
            return base.Channel.getProductOrderByOrderID(orderID);
        }
        
        public void DeleteProductOrderByIDs(int productID, int orderID) {
            base.Channel.DeleteProductOrderByIDs(productID, orderID);
        }
        
        public void UpdateOrder(Common.Order o) {
            base.Channel.UpdateOrder(o);
        }
        
        public Common.Order[] getShippedOrders(int accountID) {
            return base.Channel.getShippedOrders(accountID);
        }
        
        public Common.Order[] getPurchasesUnderWarranty(int accountID) {
            return base.Channel.getPurchasesUnderWarranty(accountID);
        }
    }
}
