//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electros.TownServ {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TownServ.ITownService")]
    public interface ITownService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITownService/GetAllTowns", ReplyAction="http://tempuri.org/ITownService/GetAllTownsResponse")]
        Common.Town[] GetAllTowns();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITownService/GetTownByID", ReplyAction="http://tempuri.org/ITownService/GetTownByIDResponse")]
        Common.Town GetTownByID(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITownServiceChannel : Electros.TownServ.ITownService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TownServiceClient : System.ServiceModel.ClientBase<Electros.TownServ.ITownService>, Electros.TownServ.ITownService {
        
        public TownServiceClient() {
        }
        
        public TownServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TownServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TownServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TownServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Common.Town[] GetAllTowns() {
            return base.Channel.GetAllTowns();
        }
        
        public Common.Town GetTownByID(int id) {
            return base.Channel.GetTownByID(id);
        }
    }
}
